apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignition-dev
  namespace: ignition-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ignition
  template:
    metadata:
      labels:
        app: ignition
    spec:
      containers:
      - name: ignition
        image: inductiveautomation/ignition:8.3-nightly # Using your current nightly image
        ports:
        - containerPort: 8088
        env:
        - name: ACCEPT_IGNITION_EULA
          value: "Y"
        - name: GATEWAY_ADMIN_USERNAME
          value: "admin"
        - name: GATEWAY_ADMIN_PASSWORD
          value: "password" # Change this in production!
        - name: IGNITION_EDITION
          value: "standard"
---
apiVersion: v1
kind: Service
metadata:
  name: ignition-service
  namespace: ignition-dev
spec:
  type: NodePort
  selector:
    app: ignition
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30088 # Access via http://localhost:30088
